version: 0.1

phases:
  build:
    commands:
      - echo Entered the build phase.....
      - mvn clean package
  post_build:
      commands:
      - echo Build completed successfully.....
      - ls -ltr
      - cd application/target/
      - ls -ltr
artifacts:
  files:
    - application/target/employeeservice.jar
  discard-paths: yes