version: 0.1

phases:
  build:
    commands:
      - echo Entered the build phase.....
      - mvn clean package
  post_build:
      commands:
      - echo Build completed successfully.....
artifacts:
  files:
    - application/target/camerascheduler.jar
  discard-paths: yes